### ISSUE TITLE
No running nginx instances

### ISSUE THREAD

**Issue by dave4you** [nginxinc/nginx-amplify-agent#162]
Hi,

I have a question:

Amplify is running fine in the sense that I have data in my Overview and Graphs. However if I go to Analyzer it states: 'No running nginx instances'.

From in Inventory perspective is stated that 1 System is up, but there no (0) NGINX found.

The agent log is filling and showing bytes being forwarded to https://receiver.amplify.nginx.com:443 all with a 202 response.

A curl http://127.0.0.1/nginx_status from the local nginx machine results in
Active connections: 1
server accepts handled requests
87 87 87
Reading: 0 Writing: 1 Waiting: 0

And directions on how to solve this issue?

Kind regards,

Dave

**Comment by SuperSpe** [comment]
I have the exact same problem.
The agent is installed in the host, the host has ngnix container.
I have graphs showing correctly, stub shows data, but othe rthe "No running nginx instances" I have all 0 data on the "Overview" tab too

**Comment by gshulegaard** [comment]
@SuperSpe I am not sure your issue is the same as the original report.  I haven't worked on Amplify for awhile but I think your problem lies with having the Agent external to the container running NGINX.

https://amplify.nginx.com/docs/guide-how-nginx-amplify-agent-works.html#detecting-and-monitoring-nginx-instances

> Note. The agent will try to detect and monitor all unique NGINX instances currently running on a host.

The agent (if it hasn't changed since I worked on it) detects running NGINX instances via `psutil` which uses the `procfs` to "see" running processes.  Generally this means that the agent has to be installed _inside_ a container in order to have adequate permissions to find the running NGINX process.

Regarding your update, even if the agent could not access the log files, many system stats would still be available so you it's likely not an issue (or a separate one).

**Comment by scyto** [comment]
I found several things are needed to get this working.

1. access to the logs, if your logs are not in the container or bind mount you should use the built-in syslog server on the amplify-agent and the configure additional access and error log entries in nginx.conf etc to point to the loopback syslog

2.if you are running in container you need to make sure the nginx process and amplify process are running as same user - this is done by setting the user root; in the main context of nginx.conf and populating the [nginx] section with the user = and if needed the path to the nginx.conf - i set both my to root and it worked.

3. no errors if you run the install.sh script - this is good for checking most deps

**Comment by podguzovvasily** [comment]
Dear Scyto,
One of the installation tests was failed. And I still not get NGINX metrics. How did you resolve that?

> 3\. no errors if you run the install.sh script - this is good for checking most deps

12. Checking if euid 0(root) can find root processes ... agent will fail to detect nginx, ps(1) is restricted!
