### ISSUE TITLE
Could not read certificate (letsencrypt, acme.sh)

### ISSUE THREAD

**Issue by StephanGeorg** [nginxinc/nginx-amplify-agent#164]
Hi.

We're using Letsencrypt SSL certificates generated and renewed with [acme.sh](http://acme.sh).

**Analyzer**
```
SSL Certificates  0
Expired   0
Warnings   0
SSL/TLS servers   16
HTTP/2 servers   16
Library   OpenSSL1.1.111 Sep 2018
```
I already changed .acme.sh folder, subfolders and certificates to the nginx user (which is nginx in my case)

```
chown -R nginx:nginx .acme.sh/
```

**/var/log/amplify-agent/agent.log**

```
2019-11-27 09:29:21,576 [15096] supervisor ssl certificate found /root/.acme.sh/domain/fullchain.cer
2019-11-27 09:29:21,576 [15096] supervisor could not read /root/.acme.sh/domain/fullchain.cer (maybe permissions?)
```

**Comment by gshulegaard** [comment]
From the log output it looks like `.acme.sh` is in `/root/` which is most likely not accessible by the agent.  I would move the cert files into a directory that is accessible by the `nginx` user.   I would not recommend changing owner of the parent `/root/` folder in this case.

I have not used the `acme.sh` script but I would guess that you might also consider running that script as the `nginx` user rather than as `root`.
