### ISSUE TITLE
etc/letsencrypt/live/<domain>/fullchain.pem

### ISSUE THREAD

**Issue by ToxineDev** [nginxinc/nginx-amplify-agent#86]
Hey tried to setup the panel was thinking i did some misstake but its not looking like that becsue 
Here is my error in terminal:

![terminal](https://user-images.githubusercontent.com/36299609/36027624-57c8ae3e-0d9c-11e8-889b-c5a5f34bbf67.PNG)

**Comment by gshulegaard** [comment]
Hi @ToxineDev, this doesn't appear to have anything to do with NGINX Amplify, the monitoring sidecar service for NGINX the web server.  Rather, this error seems directly related to NGINX itself.

More specifically, the error you are receiving seems to be because in your NGINX config you are referencing an SSL certificate file at `/etc/letsencrypt/live/<domain>/fullchain.pem` but the file doesn't exist.

I hope this little bit helps you debug, but since this is unrelated to Amplify I am going to close this issue.
